name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Buildozer and pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: buildozer-cache-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}
        restore-keys: |
          buildozer-cache-${{ runner.os }}-

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-11-jdk python3-kivy build-essential python3-dev
        pip3 install buildozer
        pip3 install Cython

    - name: Trigger SDK install
      run: buildozer android debug || true

    - name: Accept Android SDK licenses
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH
        yes | sdkmanager --licenses || echo "License acceptance Failedbut Continuing"
      

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
