name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Buildozer and pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.cache/pip
        key: buildozer-cache-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}
        restore-keys: |
          buildozer-cache-${{ runner.os }}-

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-11-jdk tree python3-kivy build-essential python3-dev
        pip3 install buildozer
        pip3 install Cython
        

    - name: Install Android SDK manually
      run: |
      
          mkdir -p $HOME/android/sdk
          cd $HOME/android
      
          # Download command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools-temp
      
          # Move into correct SDK layout
          mkdir -p sdk/cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* sdk/cmdline-tools/latest/
      
          # Set environment variables
          export ANDROID_SDK_ROOT=$HOME/android/sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
      
          # Verify sdkmanager exists
          which sdkmanager || (echo "❌ sdkmanager not found" && exit 1)
      
          # Accept licenses
          yes | sdkmanager --licenses || echo "⚠️ License acceptance failed or completed early — continuing"
      
          # Install required packages
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;25.2.9519653"

    - name: confirm location
      run: |
        ls -l /home/runner/android/sdk
        ls -l /home/runner/android/sdk/ndk

    - name: Create legacy sdkmanager symlink
      run: |
        mkdir -p $HOME/android/sdk/tools/bin
        ln -s $HOME/android/sdk/cmdline-tools/latest/bin/sdkmanager $HOME/android/sdk/tools/bin/sdkmanager

        
    #- name: Configure Buildozer to use manual SDK
     # run: |
      #  sed -i '/^android.sdk_path/d' buildozer.spec
       # echo "android.sdk_path = $HOME/android/sdk" >> buildozer.spec

    - name: Autotools setup
      run: |
        autoupdate
        autoreconf -i
        ./configure


    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
