name: Build Executable

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Use the latest Windows virtual machine for the job
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build the executable with PyInstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile Excel_Creator.py

    # Step 5: Upload the executable as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Excel_Creator
        path: D:\a\ExcelCreator\ExcelCreator\dist\Excel_Creator.exe
