name: Capture Python Dependencies (Windows)

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: windows-latest # Specifies a Windows virtual machine

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install existing project dependencies
        # This uses the default PowerShell shell on the Windows runner.
        # The | syntax is for multi-line commands within the YAML.
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl Pillow
          # Check if requirements.txt exists and install from it
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            Write-Host "No requirements.txt found, skipping direct dependency install."
          }

      - name: Generate a full, frozen requirements file
        run: |
          # Use "Out-File" or standard redirection ">" to create the file in PowerShell
          pip freeze > frozen_requirements.txt
          Write-Host "Generated frozen_requirements.txt"

      - name: Upload dependency file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dependencies-windows
          path: frozen_requirements.txt # Path is relative to the root of the repo
          retention-days: 5
